apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu
  template:
    metadata:
      labels:
        app: ubuntu
    spec:
      containers:
        - name: ubuntu
          image: ghcr.io/xluffy/olek/base:master-67d6f1a
          imagePullPolicy: Always
          command: ["sleep", "86400"]
          resources:
            limits:
              memory: "1Gi"
              cpu: "1000m"
